services:
  db:
    image: postgres:16
    container_name: studentLife_db
    restart: "no"
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    mem_limit: 1g

  app:
    build: .
    container_name: studentLife_app
    restart: "no"
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "5000:5000"
    mem_limit: 1g

volumes:
  db_data: