services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: studentLife_apis_prod
    restart: always
    expose:
      - "5000"
    deploy:
      resources:
        limits:
          memory: 1g
