spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

app.secure-cookie=true
server.forward-headers-strategy=FRAMEWORK
server.port=5000

app.frontend.url=https://student-life-platform.vercel.app