spring.application.name=StudentLifeAPIs
#
#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=5000

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

spring.jwt-secret=${SPRING_JWT_SECRET}
spring.access-token-expire=${SPRING_ACCESS_TOKEN_EXPIRE}
spring.refresh-token-expire=${SPRING_REFRESH_TOKEN_EXPIRE}

app.secure-cookie=false
#app.secure-cookie=true

# Multipart file upload settings
#spring.servlet.multipart.enabled=true
#spring.servlet.multipart.max-file-size=5MB
#spring.servlet.multipart.max-request-size=10MB

# Custom property for your upload directory
#file.upload-dir=uploads

#spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
#spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
#
#spring.security.oauth2.client.registration.google.scope=profile,email

cloudinary.cloud-name=${CLOUD_NAME}
cloudinary.api-key=${API_KEY}
cloudinary.api-secret=${API_SECRET}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend.url=http://localhost:3000
app.backend.url=https://studentlifeapis.onrender.com

# WebSocket is auto-configured, but good to define your broker settings
spring.websocket.path=/ws

#admin credential
spring.admin.username=${SPRING_ADMIN_USERNAME}
spring.admin.email=${SPRING_ADMIN_EMAIL}
spring.admin.password=${SPRING_ADMIN_PASSWORD}

#agent credential
logging.level.org.hibernate=ERROR
logging.level.com.rental=DEBUG
server.error.include-message=always
server.error.include-stacktrace=always

gemini.api.key=${SPRING_GEMINI_API_KEY}
spring.jackson.serialization.write-dates-as-timestamps=false